language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r dev-requirements.txt

script:
  - "PYTHONPATH=. py.test ."
  
notifications:
  webhooks:
    urls:
      - http://staging-learn.rmotr.com/webhooks/travis/build-finished
    on_success: always
    on_failure: always
    on_start: never
